version: "3.7"

services:
  dabatabase_ignite:
    image: postgres
    container_name: dabatabase_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - dabatabase_ignite
    depends_on:
      - dabatabase_ignite

volumes:
  pgdata:
    driver: local
